--drop table if exists dw_sige.tb_cubo_mes_acumulado; 
--create table dw_sige.tb_cubo_mes_acumulado as (
INSERT INTO dw_sige.tb_cubo_mes_acumulado (
  nr_anoletivo,
  cd_crede_sefor,
  nm_crede_sefor,
  cd_macrorregiao,
  nm_macrorregiao,
  id_municipio,
  nm_municipio,
  nm_categoria,
  id_escola_inep,
  nm_escola,
  nm_localizacao_zona,
  fl_sede,
  nm_local_funcionamento,
  cd_tipo_local,
  nm_tipo_local,
  cd_turma,
  ds_turma,
  cd_curso,
  nm_curso,
  fl_estagio_curso,
  ds_ofertaitem,
  ds_turno,
  cd_etapa_oferta,
  ds_etapa_oferta,
  fl_eja,
  fl_ppdt,
  cd_ano_final_eja,
  cd_nivel,
  ds_nivel,
  cd_etapa_aluno,
  ds_etapa_aluno,
  data_extracao,
  ds_raca,
  nm_etnia_indigena,
  ds_sexo,
  ds_localizacao_residencia,
  qtd_matriculas,
  qtd_nome_social,
  qtd_possui_cpf,
  qtd_possui_bolsa_escola,
  qtd_possui_nis,
  qtd_transporte,
  qtd_possui_deficiencia,
  qtd_deficiencia_censo,
  qtd_cegueira,
  qtd_baixa_visao,
  qtd_surdez,
  qtd_deficiencia_auditiva,
  qtd_surdocegueira,
  qtd_deficiencia_fisica,
  qtd_deficiencia_intelectual,
  qtd_deficiencia_multipla,
  qtd_autismo,
  qtd_altas_habilidades_superdotacao,
  qtd_depressao,
  qtd_discalculia,
  qtd_dislalia,
  qtd_dislexia,
  qtd_epilepsia,
  qtd_esquizofrenia,
  qtd_sindrome_de_down,
  qtd_sindrome_do_panico,
  qtd_transtorno_opositor_desafiador,
  qtd_tdah,
  qtd_visao_monocular
)
SELECT
  nr_anoletivo,
  cd_crede_sefor,
  nm_crede_sefor,
  cd_macrorregiao,
  nm_macrorregiao,
  id_municipio,
  nm_municipio,
  nm_categoria,
  id_escola_inep,
  nm_escola,
  nm_localizacao_zona,
  fl_sede,
  nm_local_funcionamento,
  cd_tipo_local,
  nm_tipo_local,
  cd_turma,
  ds_turma,
  cd_curso,
  nm_curso,
  fl_estagio_curso,
  ds_ofertaitem,
  ds_turno,
  cd_etapa_oferta,
  ds_etapa_oferta,
  fl_eja,
  fl_ppdt,
  cd_ano_final_eja,
  cd_nivel,
  ds_nivel,
  cd_etapa_aluno,
  ds_etapa_aluno,
  data_extracao,
  ds_raca,
  nm_etnia_indigena,
  ds_sexo,
  COUNT(1) AS qtd_matriculas,
  SUM(CASE WHEN nm_social IS NOT NULL THEN 1 ELSE 0 END) AS qtd_nome_social,
  SUM(fl_possui_cpf) AS qtd_possui_cpf,
  SUM(fl_possui_bolsa_escola) AS qtd_possui_bolsa_escola,
  SUM(fl_possui_nis) AS qtd_possui_nis,
  SUM(fl_transporte) AS qtd_transporte,
  SUM(fl_possui_deficiencia) AS qtd_possui_deficiencia,
  SUM(fl_deficiencia_censo) AS qtd_deficiencia_censo,
  SUM(fl_cegueira) AS qtd_cegueira,
  SUM(fl_baixa_visao) AS qtd_baixa_visao,
  SUM(fl_surdez) AS qtd_surdez,
  SUM(fl_deficiencia_auditiva) AS qtd_deficiencia_auditiva,
  SUM(fl_surdocegueira) AS qtd_surdocegueira,
  SUM(fl_deficiencia_fisica) AS qtd_deficiencia_fisica,
  SUM(fl_deficiencia_intelectual) AS qtd_deficiencia_intelectual,
  SUM(fl_deficiencia_multipla) AS qtd_deficiencia_multipla,
  SUM(fl_autismo) AS qtd_autismo,
  SUM(fl_altas_habilidades_superdotacao) AS qtd_altas_habilidades_superdotacao,
  SUM(fl_depressao) AS qtd_depressao,
  SUM(fl_discalculia) AS qtd_discalculia,
  SUM(fl_dislalia) AS qtd_dislalia,
  SUM(fl_dislexia) AS qtd_dislexia,
  SUM(fl_epilepsia) AS qtd_epilepsia,
  SUM(fl_esquizofrenia) AS qtd_esquizofrenia,
  SUM(fl_sindrome_de_down) AS qtd_sindrome_de_down,
  SUM(fl_sindrome_do_panico) AS qtd_sindrome_do_panico,
  SUM(fl_transtorno_opositor_desafiador) AS qtd_transtorno_opositor_desafiador,
  SUM(fl_tdah) AS qtd_tdah,
  SUM(fl_visao_monocular) AS qtd_visao_monocular
FROM dw_sige.tb_cubo_aluno_mes_2025 tcam
GROUP BY 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35;

---select * from dw_sige.tb_cubo_mes_acumulado --378518

--select count(1) from dw_sige.tb_cubo_aluno_mes_2025 tcam 

