create table spaece.tb_spaece_2022_mt_em as (
select
cd_projeto	::	integer	,		
nm_projeto	::	text	,		
nu_ano	::	smallint	,		
cd_estado	::	smallint 	,		
nm_estado	::	text	,		
nm_regional	::	text	,		
cd_municipio	::	integer	,		
nm_municipio	::	text	,		
cd_escola	::	integer	,		
nm_escola	::	text	,		
cd_rede	::	smallint 	,		
dc_rede	::	text	,		
cd_localizacao	::	smallint 	,		
dc_localizacao	::	text	,		
cd_turma	::	bigint 	,		
cd_turma_instituicao	::	integer	,		
nm_turma	::	text	,		
cd_turno	::	smallint 	,		
dc_turno	::	text	,		
fl_multi_turma	::	smallint 	,		
fl_anexo_turma	::	smallint 	,		
cd_ensino	::	smallint 	,		
dc_ensino	::	text	,		
cd_aluno	::	bigint 	,		
cd_aluno_institucional	::	bigint 	,		
cd_aluno_inep	::	bigint 	,		
cd_aluno_publicacao	::	bigint 	,		
nm_aluno	::	text	,		
dt_nascimento	::	text	,		
cd_sexo	::	Character(1)	,		
filiacao	::	text	,		
dc_deficiencia	::	text	,		
nm_disciplina_caderno	::	text	,		
cd_disciplina	::	smallint 	,		
nm_disciplina	::	text	,		
nm_disciplina_sigla	::	Character(2)	,		
cd_etapa_aplicacao	::	smallint 	,		
dc_etapa_aplicacao	::	text	,		
cd_etapa_avaliada	::	smallint 	,		
dc_etapa_avaliada	::	text	,		
cd_etapa	::	smallint 	,		
cd_etapa_publicacao	::	smallint 	,		
dc_etapa_publicacao	::	text	,		
cd_caderno	::	bigint 	,	-----------------------------	
dc_caderno	::	text	,		
nu_caderno	::	smallint 	,		
cd_base_versao	::	smallint 	,		
nu_sequencial	::	bigint 	,		
fl_filtros	::	smallint 	,		
dc_filtros	::	text	,		
fl_extra	::	smallint 	,		
fl_publicacao	::	smallint 	,		
dc_publicacao	::	text	,		
fl_excluido_planejada	::	smallint 	,		
fl_excluido_sujeito	::	smallint 	,		
fl_avaliado	::	smallint 	,		
fl_preenchido	::	smallint 	,		
vl_proficiencia	::	numeric	,		
vl_proficiencia_erro	::	numeric	,		
nu_pontos	::	smallint 	,		
vl_perc_acertos	::	numeric	,		
id_mascara	::	text	,		
cd_lote	::	integer	,		
nu_pacote	::	bigint 	,		
dc_imagem_cartao	::	text	,		
dc_imagem_lista	::	text	,		
dc_imagem_ata	::	text	,		
dc_imagem_reserva	::	text,		
nu_imagem	::	text 	,		
id_instrumento	::	text 	,		
tp_instrumento	::	text 	,		
dc_desenho_instrumento	::	text	,		
tp_processamento	::	text 	,		
rp	::	text	,	
rp_001	::	text	,		
rp_002	::	text	,		
rp_003	::	text	,		
rp_004	::	text	,		
rp_005	::	text	,		
rp_006	::	text	,		
rp_007	::	text	,		
rp_008	::	Character(1)	,		
rp_009	::	Character(1)	,		
rp_010	::	Character(1)	,		
rp_011	::	Character(1)	,		
rp_012	::	Character(1)	,		
rp_013	::	Character(1)	,		
rp_014	::	Character(1)	,		
rp_015	::	Character(1)	,		
rp_016	::	Character(1)	,		
rp_017	::	Character(1)	,		
rp_018	::	Character(1)	,		
rp_019	::	Character(1)	,		
rp_020	::	Character(1)	,		
rp_021	::	Character(1)	,		
rp_022	::	Character(1)	,		
rp_023	::	Character(1)	,		
rp_024	::	Character(1)	,		
rp_025	::	Character(1)	,		
rp_026	::	Character(1)	,		
rp_027	::	Character(1)	,		
rp_028	::	Character(1)	,		
rp_029	::	Character(1)	,		
rp_030	::	Character(1)	,		
rp_031	::	Character(1)	,		
rp_032	::	Character(1)	,		
rp_033	::	Character(1)	,		
rpa_001	::	text	::	smallint	,
rpa_002	::	text	::	smallint	,
rpa_003	::	text	::	smallint	,
rpa_004	::	text	::	smallint	,
rpa_005	::	text	::	smallint	,
rpa_006	::	text	::	smallint	,
rpa_007	::	text	::	smallint	,
rpa_008	::	text	::	smallint	,
rpa_009	::	text	::	smallint	,
rpa_010	::	text	::	smallint	,
rpa_011	::	text	::	smallint	,
rpa_012	::	text	::	smallint	,
rpa_013	::	text	::	smallint	,
rpa_014	::	text	::	smallint	,
rpa_015	::	text	::	smallint	,
rpa_016	::	text	::	smallint	,
rpa_017	::	text	::	smallint	,
rpa_018	::	text	::	smallint	,
rpa_019	::	text	::	smallint	,
rpa_020	::	text	::	smallint	,
rpa_021	::	text	::	smallint	,
rpa_022	::	text	::	smallint	,
rpa_023	::	text	::	smallint	,
rpa_024	::	text	::	smallint	,
rpa_025	::	text	::	smallint	,
rpa_026	::	text	::	smallint	,
nu_posicao_lista	::	smallint 	,		
rp_lista	::	Character(1)	,		
regional_fortaleza	::	Character(6)	,		
cd_regional	::	smallint 	,		
d016_acerto	::	smallint 	,		
d016_total	::	smallint 	,		
d019_acerto	::	smallint 	,		
d019_total	::	smallint 	,		
d020_acerto	::	smallint 	,		
d020_total	::	smallint 	,		
d024_acerto	::	smallint 	,		
d024_total	::	smallint 	,		
d028_acerto	::	smallint 	,		
d028_total	::	smallint 	,		
d040_acerto	::	smallint 	,		
d040_total	::	smallint 	,		
d042_acerto	::	smallint 	,		
d042_total	::	smallint 	,		
d049_acerto	::	smallint 	,		
d049_total	::	smallint 	,		
d050_acerto	::	smallint 	,		
d050_total	::	smallint 	,		
d051_acerto	::	smallint 	,		
d051_total	::	smallint 	,		
d052_acerto	::	smallint 	,		
d052_total	::	smallint 	,		
d053_acerto	::	smallint 	,		
d053_total	::	smallint 	,		
d054_acerto	::	smallint 	,		
d054_total	::	smallint 	,		
d055_acerto	::	smallint 	,		
d055_total	::	smallint 	,		
d056_acerto	::	smallint 	,		
d056_total	::	smallint 	,		
d057_acerto	::	smallint 	,		
d057_total	::	smallint 	,		
d058_acerto	::	smallint 	,		
d058_total	::	smallint 	,		
d064_acerto	::	smallint 	,		
d064_total	::	smallint 	,		
d065_acerto	::	smallint 	,		
d065_total	::	smallint 	,		
d067_acerto	::	smallint 	,		
d067_total	::	smallint 	,		
d071_acerto	::	smallint 	,		
d071_total	::	smallint 	,		
d072_acerto	::	smallint 	,		
d072_total	::	smallint 	,		
d076_acerto	::	smallint 	,		
d076_total	::	smallint 	,		
d078_acerto	::	smallint 	,		
d078_total	::	smallint 	,		
distrito_fortaleza	::	text	,		
sefor_fortaleza	::	text	,		
fl_esc_especiais	::	smallint 	,		
fl_eeep	::	smallint 	,		
nm_etnia	::	text	,		
cd_escola_original	::	integer	,		
fl_transferido	::	smallint	,		
dc_transferido	::	text	,		
fl_laudo	::	smallint	,		
fl_retirar	::	smallint	,		
dc_laudo	::	text	,		
dc_spaece	::	text	,		
cd_turma_hist	::	bigint 	,		
nm_turma_hist	::	text	,		
ds_arquivo	::	text	,		
id_spaece_ceipe	::	integer		
from public.temp_1 t 
)
