create table spaece.tb_spaece_2022_lp_2ano as (
select 
cd_projeto  ::  integer ,
nm_projeto  ::  text  ,
nu_ano  ::  smallint  ,
cd_estado ::  smallint  ,
nm_estado ::  text  ,
nm_regional ::  text  ,
cd_municipio  ::  integer ,
nm_municipio  ::  text  ,
cd_escola ::  integer ,
nm_escola ::  text  ,
cd_rede ::  smallint  ,
dc_rede ::  text  ,
cd_localizacao  ::  smallint  ,
dc_localizacao  ::  text  ,
cd_turma  ::  bigint  ,
cd_turma_instituicao  ::  integer ,
nm_turma  ::  text  ,
cd_turno  ::  smallint  ,
dc_turno  ::  text  ,
fl_multi_turma  ::  smallint  ,
fl_anexo_turma  ::  smallint  ,
cd_ensino ::  smallint  ,
dc_ensino ::  text  ,
cd_aluno  ::  bigint  ,
cd_aluno_institucional  ::  bigint  ,
cd_aluno_inep ::  bigint  ,
cd_aluno_publicacao ::  bigint  ,
nm_aluno  ::  text  ,
dt_nascimento ::  text  ,
cd_sexo ::  Character(1)  ,
filiacao  ::  text  ,
dc_deficiencia  ::  text  ,
nm_disciplina_caderno ::  text, 
cd_disciplina ::  smallint  ,
nm_disciplina ::  text  ,
nm_disciplina_sigla ::  Character(2)  ,
cd_etapa_aplicacao  ::  smallint  ,
dc_etapa_aplicacao  ::  text  ,
cd_etapa_avaliada ::  smallint  ,
dc_etapa_avaliada ::  text  ,
cd_etapa  ::  smallint  ,
cd_etapa_publicacao ::  smallint  ,
dc_etapa_publicacao ::  text  ,
cd_caderno  ::  bigint ,  
dc_caderno  ::  text  ,
nu_caderno  ::  smallint ,  
cd_base_versao  ::  smallint  ,
nu_sequencial ::  bigint ,  
fl_filtros  ::  smallint ,  
dc_filtros  ::  text  ,
fl_extra  ::  smallint  ,
fl_publicacao ::  smallint  ,
dc_publicacao ::  text  ,
fl_excluido_planejada ::  smallint  ,
fl_excluido_sujeito ::  smallint  ,
fl_avaliado ::  smallint  ,
fl_preenchido ::  smallint  ,
vl_proficiencia ::  numeric ,
vl_proficiencia_erro  ::  numeric ,
nu_pontos ::  smallint  ,
vl_perc_acertos ::  numeric ,
id_mascara  ::  text  ,
cd_lote ::  integer ,
nu_pacote ::  bigint  ,
dc_imagem_cartao  ::  text  ,
dc_imagem_lista ::  text  ,
dc_imagem_ata ::  text  ,
dc_imagem_reserva ::  text  ,
nu_imagem ::  text  ,
id_instrumento  ::  text  ,
tp_instrumento  ::  smallint  ,
dc_desenho_instrumento  ::  text  ,
tp_processamento  ::  text  ,
rp  ::  text     ,
rp_001  ::  text  ,
rp_002  ::  text  ,
rp_003  ::  text  ,
rp_004  ::  text  ,
rp_005  ::  text  ,
rp_006  ::  text  ,
rp_007  ::  text  ,
rp_008  ::  Character(1)  ,
rp_009  ::  Character(1)  ,
rp_010  ::  Character(1)  ,
rp_011  ::  Character(1)  ,
rp_012  ::  Character(1)  ,
rp_013  ::  Character(1)  ,
rp_014  ::  Character(1)  ,
rp_015  ::  Character(1)  ,
rp_016  ::  Character(1)  ,
rp_017  ::  Character(1)  ,
rp_018  ::  Character(1)  ,
rp_019  ::  Character(1)  ,
rp_020  ::  Character(1)  ,
rp_021  ::  Character(1)  ,
rp_022  ::  Character(1)  ,
rp_023  ::  Character(1)  ,
rp_024  ::  Character(1)  ,
rp_025  ::  Character(1)  ,
rp_026  ::  Character(1)  ,
rp_027  ::  Character(1)  ,
rp_028  ::  Character(1)  ,
rp_029  ::  Character(1)  ,
rp_030  ::  Character(1)  ,
rp_031  ::  Character(1)  ,
rp_032  ::  Character(1)  ,
rp_033  ::  Character(1)  ,
rpa_001 ::  text :: smallint  ,
rpa_002 ::  text :: smallint  ,
rpa_003 ::  text :: smallint  ,
rpa_004 ::  text :: smallint  ,
rpa_005 ::  text :: smallint  ,
rpa_006 ::  text :: smallint  ,
rpa_007 ::  text :: smallint  ,
rpa_008 ::  text :: smallint  ,
rpa_009 ::  text :: smallint  ,
rpa_010 ::  text :: smallint  ,
rpa_011 ::  text :: smallint  ,
rpa_012 ::  text :: smallint  ,
rpa_013 ::  text :: smallint  ,
rpa_014 ::  text :: smallint  ,
rpa_015 ::  text :: smallint  ,
rpa_016 ::  text :: smallint  ,
rpa_017 ::  text :: smallint  ,
rpa_018 ::  text :: smallint  ,
rpa_019 ::  text :: smallint  ,
rpa_020 ::  text :: smallint  ,
rpa_021 ::  text :: smallint  ,
rpa_022 ::  text :: smallint  ,
rpa_023 ::  text :: smallint  ,
rpa_024 ::  text :: smallint  ,
rpa_025 ::  text :: smallint  ,
rpa_026 ::  text :: smallint  ,
nu_posicao_lista  ::  smallint  ,
rp_lista  ::  Character(1)  ,
regional_fortaleza  ::  Character(6)  ,
cd_regional ::  smallint  ,
d001_acerto ::  text :: smallint,
d001_total  ::  text :: smallint,
d002_acerto ::  text :: smallint,
d002_total  ::  text :: smallint,
d003_acerto ::  text :: smallint,
d003_total  ::  text :: smallint,
d004_acerto ::  text :: smallint,
d004_total  ::  text :: smallint,
d005_acerto ::  text :: smallint,
d005_total  ::  text :: smallint,
d006_acerto ::  text :: smallint,
d006_total  ::  text :: smallint,
d007_acerto ::  text :: smallint,
d007_total  ::  text :: smallint,
d008_acerto ::  text :: smallint,
d008_total  ::  text :: smallint,
d009_acerto ::  text :: smallint,
d009_total  ::  text :: smallint,
d010_acerto ::  text :: smallint,
d010_total  ::  text :: smallint,
d011_acerto ::  text :: smallint,
d011_total  ::  text :: smallint,
d012_acerto ::  text :: smallint,
d012_total  ::  text :: smallint,
d013_acerto ::  text :: smallint,
d013_total  ::  text :: smallint,
d014_acerto ::  text :: smallint,
d014_total  ::  text :: smallint,
d015_acerto :: text ::  smallint  ,
d015_total  ::   text ::  smallint  ,
d016_acerto ::   text ::  smallint  ,
d016_total  ::   text ::  smallint  ,
d017_acerto ::   text ::  smallint  ,
d017_total  ::   text ::  smallint  ,
d018_acerto ::   text ::  smallint  ,
d018_total  ::   text ::  smallint  ,
d019_acerto ::   text ::  smallint  ,
d019_total  ::   text ::  smallint  ,
d020_acerto ::   text ::  smallint  ,
d020_total  ::   text ::  smallint  ,
d021_acerto ::   text ::  smallint  ,
d021_total  ::   text ::  smallint  ,
d022_acerto ::   text ::  smallint  ,
d022_total  ::   text ::  smallint  ,
d023_acerto ::   text ::  smallint  ,
d023_total  ::   text ::  smallint  ,
d024_acerto ::   text ::  smallint  ,
d024_total  ::   text ::  smallint  ,
d025_acerto ::   text ::  smallint  ,
d025_total  ::   text ::  smallint  ,
d026_acerto ::   text ::  smallint  ,
d026_total  ::   text ::  smallint  ,
d027_acerto ::   text ::  smallint  ,
d027_total  ::   text ::  smallint  ,
d028_acerto ::   text ::  smallint  ,
d028_total  ::   text ::  smallint  ,
d029_acerto ::   text ::  smallint  ,
d029_total  ::   text ::  smallint  ,
distrito_fortaleza  ::  text  ,
sefor_fortaleza ::  text  ,
fl_esc_especiais  ::  smallint  ,
fl_eeep ::  smallint  ,
nm_etnia  ::  text  ,
cd_escola_original  ::  integer ,
fl_transferido  ::  smallint  ,
dc_transferido  ::  text  ,
fl_laudo  ::  smallint  ,
fl_retirar  ::  smallint  ,
dc_laudo  ::  text  ,
dc_spaece ::  text  ,
cd_turma_hist ::  bigint  ,
nm_turma_hist ::  text  ,
id_spaece_ceipe ::  numeric ,
ds_arquivo  ::  text 
from public.temp_1 t 
)