select 
nr_anoletivo,
id_crede_sefor,
nm_crede_sefor,
id_municipio,
nm_municipio,
cd_categoria cd_categoria_escola,
ds_categoria ds_categoria_escola,
tde.id_escola_inep,
nm_escola,
ap.cd_raca,
ap.ds_raca,
ap.cd_sexo,
ap.ds_sexo,
ea.cd_turno,
ea.ds_turno,
--ap.fl_bolsaescola,
count(1) total,
sum(case when cd_etapa_aluno = 1 then 1 else 0 end) total_infantil,
sum(case when cd_etapa_sige = 180 then 1 else 0 end) creche,
sum(case when cd_etapa_sige = 181 then 1 else 0 end) pre_escola,
sum(case when cd_etapa_aluno = 2 and cd_oferta_ensino = 1 then 1 else 0 end) total_fund,
sum(case when cd_subetapa = 1 and cd_oferta_ensino = 1 then 1 else 0 end) fund_ai,
sum(case when cd_subetapa = 2 and cd_oferta_ensino = 1 then 1 else 0 end) fund_af,
sum(case when cd_ano_serie = 1 then 1 else 0 end ) a1_fund,
sum(case when cd_ano_serie = 2 then 1 else 0 end ) a2_fund,
sum(case when cd_ano_serie = 3 then 1 else 0 end ) a3_fund,
sum(case when cd_ano_serie = 4 then 1 else 0 end ) a4_fund,
sum(case when cd_ano_serie = 5 then 1 else 0 end ) a5_fund,
sum(case when cd_ano_serie = 6 then 1 else 0 end ) a6_fund,
sum(case when cd_ano_serie = 7 then 1 else 0 end ) a7_fund,
sum(case when cd_ano_serie = 8 then 1 else 0 end ) a8_fund,
sum(case when cd_ano_serie = 9 then 1 else 0 end ) a9_fund,
sum(case when cd_etapa_aluno = 3 and cd_oferta_ensino = 1 then 1 else 0 end) medio_total_r,
sum(case when cd_ano_serie = 10 then 1 else 0 end) medio_1_serie,
sum(case when cd_ano_serie = 11 then 1 else 0 end) medio_2_serie,
sum(case when cd_ano_serie = 12 then 1 else 0 end) medio_3_serie,
sum(case when cd_ano_serie = 13 then 1 else 0 end) medio_4_serie,
sum(case when cd_etapa_sige in (213,214,195,194,175,196,174,173)then 1 else 0 end)  Total_ejas,
sum(case when cd_etapa_sige in (194,195,175,196,213,214) then 1 else 0 end) total_eja_pres,
sum(case when cd_etapa_sige in (194,195,175) then 1 else 0 end) eja_fund_p,
sum(case when cd_etapa_sige =196 then 1 else 0 end) eja_medio,
sum(case when cd_etapa_sige in(213,214) then 1 else 0 end) eja_qualifica,
sum(case when cd_etapa_sige in (173,174) then 1 else 0 end) eja_semi_total,
sum(case when cd_etapa_sige = 173 then 1 else 0 end) eja_semi_funda,
sum(case when cd_etapa_sige = 174 then 1 else 0 end) eja_semi_medio,
sum(fl_turma_ppl) qtd_aluno_ppl,
sum(fl_especial) qtd_aluno_especial,
sum(ap.fl_transporte) qdt_transporte
from public.tb_dm_etapa_aluno_2023_03_21 ea
join public.tb_dm_aluno_pessoa_2023_03_21 ap using(cd_aluno)
join public.tb_dm_escola tde using(id_escola_sige,nr_anoletivo)
where
ea.cd_etapa_aluno in (1,2,3)
group by 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15